dist: trusty
sudo: false

language: python
python:
  - "2.7"

cache: pip

notifications:
  email: false

git:
  depth: 10

services:
  - docker

env:
  - TEST_ARG="make test-jmodelica"
  #- TEST_ARG="make test-documentation"

before_install:
   - if [[ "$TEST_ARG" == *test-jmodelica* ]]; then
        docker pull michaelwetter/ubuntu-1804_jmodelica_trunk;
     fi;

# Install dependencies
# For sphinx, we need to install specific package versions, otherwise
# the html output may have small formatting differences which causes
# the test to fail
install:
  - pip install --upgrade
  - pip install lxml Jinja2
  - pip install sphinx==1.5.1 sphinx-bootstrap-theme==0.4.13 \
      sphinxcontrib-bibtex==0.3.4 sphinxcontrib-plantuml==0.8.1
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra
  #     alabaster==0.7.10 MarkupSafe==0.23 html5lib==0.999 \
  #     Pygments==2.1.3 snowballstemmer==1.2.1 docutils==0.13.1 \
  #     Babel==2.3.4 requests==2.12.4 Jinja2==2.8.1 latexcodec==1.0.4 \
  #     pybtex==0.20.1 pybtex-docutils==0.2.1 oset==0.1.3 PyYAML==3.12

# Execute tests
script:
  - $TEST_ARG
